### ISSUE TITLE
Guild Ranks are not saved properly(GuildBank)

### ISSUE THREAD

**Issue by St0rmbringer** [St0rmbringer/SD-Bugtracker#9]
The Guild ranks do not work properly, if you are for example the rank officer and the guildmaster granted you rights to take money from the bank you cannot take the money. So something is wrong there..

**Comment by Insn43** [comment]
I did some updates in the Guild Script - not it works better, but still not properly D:

**Comment by St0rmbringer** [comment]
I did some updates in the Guild script - now it works better, but still not properly D:

**Comment by St0rmbringer** [comment]
Fixed in b52ae22
